### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by drewsonne** [physera/onelogin-aws-cli#116]
If a password changes in onelogin or downstream Identity Provider, the user must go to their OS keychain, find the password entry, and delete the entry manually.

## Expected Behavior
`onelogin-aws-cli` should manage the statefulness of configurations and settings it creates, and should therefore have an option to allow a user to reset their password without understanding how the password is stored.

## Current Behavior
The user must go to the OS keychain handler, find the entry, and delete it themselves.

## Possible Solution
Add a CLI option to allow the user to reset their password

## Steps to Reproduce
1. Create configuration file with `save_password=yes` set.
2. Run `onelogin-aws-login`
3. When prompted with `Onelogin Password:` enter an incorrect password and finish all prompts.
4. Run `onelogin-aws-login` again and notice that the incorrect password is reused and is unable to be cleared.

## Context (Environment)
When users either enter an incorrect password or their password is changed upstream, they should be able to manage this without understanding how the utility stores passwords.

**Comment by slycoder** [comment]
Done in #117
