### ISSUE TITLE
Doesn't work with AWS China (and presumably Gov) accounts

### ISSUE THREAD

**Issue by kubrickfr** [physera/onelogin-aws-cli#125]
## Expected Behavior
Ideally, onelogin-aws-cli should detect from the the Destination attibute in the SAML response that the request is for China, the response contains:
`<samlp:Response xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="Rce100dcf22acc5c3a0610870db3956f59bc27d57" Version="2.0" IssueInstant="2018-07-10T14:59:14Z" Destination="https://signin.amazonaws.cn/saml">`

## Current Behavior
The following error is printed:
`An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithSAML operation: Specified provider doesn't exist (Service: AWSOpenIdDiscoveryService; Status Code: 400; Error Code: AuthSamlManifestNotFoundException; Request ID: d01a459a-8451-11e8-aa5b-xx)`

## Possible Solution
As a workaround, one can export of prefix execution with
`AWS_DEFAULT_REGION=cn-north-1`

## Steps to Reproduce
Set-up a Chinese AWS account in OneLogin and try getting credentials with onelogin-aws-cli

**Comment by slycoder** [comment]
Thanks for reporting this.  Note that you can also update your `~/.aws/config` file to set `region=cn-north-1`.  

How would you feel if we had a command line parameter to specify the region?

**Comment by kubrickfr** [comment]
I think it would be best to have it in the configuration file too as AWS China has to be a different app in OneLogin, therefore has a different app number and as such needs a separate configuration section anyway.

**Comment by slycoder** [comment]
Makes sense.  I won't have time to get to this in the near future but if you send a PR I'd be happy to merge it in.

**Comment by ow-krioles** [comment]
I've added a region configuration option to the command line and in the configuration file, and would like to submit as a PR.

**Comment by kubrickfr** [comment]
PR #127 doesn't seem to help / work for China.
I've tried adding `--region cn-north-1` as an argument and / or in the configuration file and I still get the same error.

**Comment by slycoder** [comment]
Is the region getting written to your `~/.aws/config`?

**Comment by slycoder** [comment]
Are you trying to write to the default profile?  What happens if you don't specify the profile --- does the profile named after the arn have the correct region?

**Comment by kubrickfr** [comment]
Are you trying to write to the default profile?
No

What happens if you don't specify the profile 
Then it connects to the default profile which is standard US and works fine.

Does the profile named after the arn have the correct region?
Do you mean in my `~/.aws/credentials`? yes, the profile onelogin-aws-cli is supposed to write to has the correct region.

**Comment by slycoder** [comment]
Yeah, so I'm a bit confused by those responses.  When you try to access an AWS service using the aforementioned profile (in the cn region), does it not work?  Unless you go out of your way to specify it as such, the tool is not going to overwrite your default aws profile, only the aws profile associated with your onelogin arn

**Comment by kubrickfr** [comment]
So, if I use my workaround :
`AWS_DEFAULT_REGION=cn-north-1 onelogin-aws-login -C china`
It works fine.

But I would expect that setting the region in `~/.onelogin-aws.config` would allow me to just launch:
`onelogin-aws-login -C china`
but it doesn't work, even if I add `--region cn-north-1` to the command line.

**Comment by kubrickfr** [comment]
FYI, the following patch fixes the issue:
```patch
diff --git a/onelogin_aws_cli/__init__.py b/onelogin_aws_cli/__init__.py
index f73d90d..ec4fbed 100644
--- a/onelogin_aws_cli/__init__.py
+++ b/onelogin_aws_cli/__init__.py
@@ -148,6 +148,8 @@ class OneloginAWS(object):
 
         if not self.role_arn:
             self.get_role()
+        if self.config['region']:
+            self.sts_client = boto3.client("sts", region_name=self.config['region'])
         res = self.sts_client.assume_role_with_saml(
             RoleArn=self.role_arn,
             PrincipalArn=self.principal_arn,
```

**Comment by kubrickfr** [comment]
Does this clarify what I'm trying to achieve?

**Comment by slycoder** [comment]
Yeah, I think I understand now.  Do you think you could send a PR?

**Comment by slycoder** [comment]
PR has been merged.  Thanks @tuxinaut !

**Comment by slycoder** [comment]
And thanks for @kubrickfr  for patiently explaining the issue!
