### ISSUE TITLE
Show export AWS environment variables in current shell

### ISSUE THREAD

**Issue by youracetech** [physera/onelogin-aws-cli#126]
To have feature parity with https://github.com/onelogin/onelogin-aws-cli-assume-role , it should print out the export AWS environment variables for the user in the current shell.  This also helps with Terraform users, as there is no way to specify an AWS profile.

## Expected Behavior

After successful authentication, it should print out the commands to set these as the current AWS environment variables.

## Current Behavior

credentials get cached in a different file

## Possible Solution

print the export AWS environment variables for the user in the current shell.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

I'm trying to run terraform with onelogin-aws-login unsuccessfully

## Possible Implementation

Please see pull request export_aws_variables
https://github.com/physera/onelogin-aws-cli/issues/126

**Comment by slycoder** [comment]
Happy to look at any PR, but the FYI credentials are cached in the normal place (~/.aws/credentials).  It prints the profile name to the command line already, something like:

```
123456789/OneLoginRole/your_id
```

So you can just set that as your aws profile when running terraform, i.e.,

```
AWS_PROFILE=123456789/OneLoginRole/your_id terraform your_commands
```

If you want to just override the `default` aws profile when running this command, you can just use the profile argument to this app,

```
onelogin-aws-login --profile default
```

**Comment by youracetech** [comment]
Thanks for that bit of information. The —profile argument wasn’t too clear in the documentation that it creates a new profile name. I made a short change() function for ~./bashrc that exports AWS_PROFILE=$1 which works very well for our needs.

Cheers,

Matthew
