### ISSUE TITLE
Launch fails on Windows (*not* WSL) if username has unicode

### ISSUE THREAD

**Issue by kubrickfr** [physera/onelogin-aws-cli#130]
launching onelogin-aws-client complains about a unicode character in helper script which contains the full path (therefore containing unicode characters) of the python interpreter

## Expected Behavior
The helper script shoud contain the appropriate header for unicode encoding

**Comment by slycoder** [comment]
Do you have a stack trace?  AFAIK, the header only affects the actual body of the script which shouldn't be affected based on where the file is located.

**Comment by kubrickfr** [comment]
`C:\Users\François>onelogin-aws-login
  File "C:\Users\François\AppData\Local\Programs\Python\Python36\Scripts\onelogin-aws-login-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xe7' in file C:\Users\François\AppData\Local\Programs\Python\Python36\Scripts\onelogin-aws-login-script.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

The line in question is:
`#!c:\users\françois\appdata\local\programs\python\python36\python.exe`

**Comment by slycoder** [comment]
The script you're mentioning isn't actually a part of this package --- it's created by your installer.

See here: https://github.com/pypa/pip/issues/5539

**Comment by kubrickfr** [comment]
Mh, I don't know why they closed that issue, I'll go ahead and re-open it, thanks.
