### ISSUE TITLE
out of date pip package

### ISSUE THREAD

**Issue by emoshaya** [physera/onelogin-aws-cli#139]
when i run pip install onelogin-aws-cli, it installs 0.1.15 which is not the latest

https://pypi.org/project/onelogin-aws-cli/

**Comment by slycoder** [comment]
I'll update the version pypi later tonight.

**Comment by slycoder** [comment]
I've pushed out the new version to pypi.  Release notes will be updated shortly.

**Comment by e-moshaya** [comment]
Hi @slycoder just checked again and 0.1.16 is latest... Shouldn't i be 1.16 the same as the latest tag in this repo?

**Comment by slycoder** [comment]
It's 0.1.16.  I tried pulling just now from pypi and it seems up to date:

```
onelogin-aws-login -v       
onelogin-aws-login 0.1.16
```

What output is pip providing you?

**Comment by e-moshaya** [comment]
@slycoder the latest version based on your releases is 1.16 https://github.com/physera/onelogin-aws-cli/releases

after installing 0.1.16 using latest pip version and run:

onelogin-aws-login -v

output is:

`usage: onelogin-aws-login [-h] [-c] [-C CONFIG_NAME] [--profile PROFILE]
[-u USERNAME] [-r RENEWSECONDS]
onelogin-aws-login: error: unrecognized arguments: -v`

This indicates it's using an old version as it doesn't support -v option

**Comment by slycoder** [comment]
Sorry for the confusion --- the release naming hasn't been consistent but 0.1.16 is indeed the latest version.

I'm not sure why you aren't picking it up though, that's why I wanted to see what pip is reporting for you.
