### ISSUE TITLE
add alias or name option

### ISSUE THREAD

**Issue by azihsoyn** [physera/onelogin-aws-cli#16]
Hi, this cli is awesome!

If output config name is changable, more useful for me.

like here
```
$ onelogin-aws-login --config_name hoge --alias default

$ cat ~/.aws/credentials
[default] <--- alias name
aws_access_key_id = ***
aws_secret_access_key = ***
aws_session_token = ***
```

Thanks.

**Comment by slycoder** [comment]
This sounds like a useful feature.  I'm pretty busy at the moment but if you wanna send a pull request, we'd be happy to get this in.
