### ISSUE TITLE
Suggestion: A self-contained binary for easier installation

### ISSUE THREAD

**Issue by mumoshu** [physera/onelogin-aws-cli#29]
In my organization, dozens of devs are starting to use onelogin-aws-cli(Thank you very much for creating/maintaining this!). The only and largest struggle for me is that many of them already has a working python2 and/or python3 envs each with virutalenv(s) or no virtualenv at all. There seems like no uniform, easy way to keep one's `onelogin-aws-login` installation up-to-date and accessible whatever python/virutualenv he/she uses for ones own development work.

## Possible solution

While hanging around GitHub, I got to know that there's a tool named [pex](https://github.com/pantsbuild/pex) which is capable of creating a self-contained executable python env for your app.

See how it works in the wild at e.g.: https://github.com/datawire/forge/commit/6fd6d6d048e345fd95ea6e683c3acff1c0f2ea4e

Would you mind hosting the self-contained binary at GitHub releases of this project once if I contributed the script for automating it?

Thanks!

**Comment by slycoder** [comment]
Sure thing!

**Comment by slycoder** [comment]
Thanks @mumoshu !

**Comment by mumoshu** [comment]
Hi @slycoder, I've just submitted a PR at #30 for this.
Would you mind reviewing it?
Thanks!

**Comment by drewsonne** [comment]
@mumoshu How did you get the dist stage to successfully build? I'm trying to debug this, but it requires lxml for all possible platforms being built.

As lxml is distributed only as platform specific wheels, I've tried download only the specific platform, but they do not seem to match your platforms in pex. What was the configuration you used when testing this to build on all the specified platforms?
