### ISSUE TITLE
Bug: Token expiration if `--renew-seconds` is longer than 5 minutes

### ISSUE THREAD

**Issue by drewsonne** [physera/onelogin-aws-cli#64]
## Expected Behavior
`onelogin-aws-login` should provide constraints for `--renew-seconds` or provide a period less than or equal to the max onelogin session time (of 10 hours), without erroring or displaying stack traces.

## Current Behavior
When setting a refresh period of greater than 5 minutes, the AWS token for SAML issuance, an error is thrown.

```
Traceback (most recent call last):
  File "/Users/development/onelogin-aws-cli/.direnv/python-3.6.3/bin/onelogin-aws-login", line 11, in <module>
    load_entry_point('onelogin-aws-cli', 'console_scripts', 'onelogin-aws-login')()
  File "/Users/development/onelogin-aws-cli/onelogin_aws_cli/cli.py", line 90, in login
    api.save_credentials()
  File "/Users/development/onelogin-aws-cli/onelogin_aws_cli/__init__.py", line 167, in save_credentials
    self.assume_role()
  File "/Users/development/onelogin-aws-cli/onelogin_aws_cli/__init__.py", line 156, in assume_role
    SAMLAssertion=self.saml.saml_response
  File "/Users/development/onelogin-aws-cli/.direnv/python-3.6.3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/development/onelogin-aws-cli/.direnv/python-3.6.3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ExpiredTokenException: An error occurred (ExpiredTokenException) when calling the AssumeRoleWithSAML operation: Token must be redeemed within 5 minutes of issuance
```
## Possible Solution

1. Provide a constraint on the `--renew-seconds` whereby values longer than 5 minutes are not allowed. The user would be provided with useful feedback before authentication occurs.
2. Inspect the expiration date in the AWS response and schedule the renew to automatically occur at that time period.
3. Ensure the onelogin SAML auth token is refreshed before it expires.

## Steps to Reproduce
1. Run `$ onelogin-aws-login --renew-seconds 330`.
2. Perform authentication.
3. Wait for 5 and a half minutes.

## Context (Environment)
There are no suggestions that there should be min/max renew periods. This could be a problem for a large userbase in terms of rate throttling if a period less than 5 minutes is required for the refresh.

It also breaks base functionality as described in the readme.

**Comment by drewsonne** [comment]
@slycoder @cameronmarlow It looks like this may be a road block in getting this and #36 functionality finished.
https://stackoverflow.com/questions/40336144/aws-api-credentials-with-onelogin-saml-and-mfa

**Comment by slycoder** [comment]
That's a super bummer.  It sounds like other people have tried implementing the same functionality as well =(. 

I can't think of another approach ... we might have to resort to somehow making entering the mfa every hour as easy as possible.

**Comment by drewsonne** [comment]
@slycoder yeah, I think for the time being that should be the goal. 

It is a pity though. Seems that there are roadblocks everywhere to get around AWS’s arbitrary 1 hour limit on their SAML credentials session. Rather frustrating.

**Comment by drewsonne** [comment]
I am also considering picking up the daemon work in the future after the above work, under the assumption that they will release the MFA-less SAML reissue in the future.

**Comment by drewsonne** [comment]
Will be made redundant by #71  and can be closed when that is merged in.

**Comment by drewsonne** [comment]
Handled by #72
