### ISSUE TITLE
OneLogin credential

### ISSUE THREAD

**Issue by chrono** [physera/onelogin-aws-cli#7]
I assume this is intended to be installed on the machines of developers / ops people who need to have AWS cli access.

This code seems to make use of the [OneLogin events API](https://developers.onelogin.com/api-docs/1/events/create-event), which requires the token to have very high privileges:

> This API can be called using either the Manage users or Manage All scope.

I propose to remove this call so that the privilege of this token can be "Authorization Only" and can be distributed to end users.

AWS sessions can be tracked on AWS end via cloudtrail.

**Comment by cameronmarlow** [comment]
This was originally intended to create events for logins so that there would be a record in onelogin of assumed roles through the API. I filed a bug and they have since resolved it, I will post a PR shortly.
