### ISSUE TITLE
Allow assumed role to be preselected in config

### ISSUE THREAD

**Issue by mumoshu** [physera/onelogin-aws-cli#82]
Similarly to #62, I have 10 or so assumed roles per AWS app, and I'm prompted to choose one of them each time I try to login.

This turned out to be a slight issue when I tried to instruct my colleagues to move from never-expiring AWS key id/secret key pair + MFA to OneLogin for SSO.

If you think this is valid, I'd like to suggest adding a `role_arn` option to the config file so that one can preselect it in the defaults and/or per specific config profile.

```
[defaults]
base_uri = https://api.us.onelogin.com/
subdomain = mycompany
username = john@mycompany.com
save_password = yes
client_id = f99ee51f00400649280db1028ffa3ca9b21b680f2189b238d342cc8158c401c7
client_secret = a85234b6db01a29a493e2422d7930dffe6f4d3a826270a18838574f6b8ef7c3e

[testing]
aws_app_id = 555029
role_arn = <arn of the role i want to assume>
```

**Comment by slycoder** [comment]
This is now available in v1.11 on pypi.
